// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrc2YzVNLst6Ed8A1qwuT050i9rTWbbF8',
    appId: '1:37390908440:web:12eb0e4b425057de5a976d',
    messagingSenderId: '37390908440',
    projectId: 'learnock-72109',
    authDomain: 'learnock-72109.firebaseapp.com',
    storageBucket: 'learnock-72109.firebasestorage.app',
    measurementId: 'G-519CGCFVE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2PVGxdgTr3WKEhZQpbYcRfdEaHWNzb8',
    appId: '1:37390908440:android:81e9c6202995746c5a976d',
    messagingSenderId: '37390908440',
    projectId: 'learnock-72109',
    storageBucket: 'learnock-72109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCt8uHtU8bTfDt1CpRLkP-QN4Z-UI_2gk',
    appId: '1:37390908440:ios:cdbd6b653f6d1eb85a976d',
    messagingSenderId: '37390908440',
    projectId: 'learnock-72109',
    storageBucket: 'learnock-72109.firebasestorage.app',
    iosBundleId: 'com.learnock.app',
  );

}